name: databricks-cicd

on:
 push:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      

      - name: airflow cicd
        run: | 
             mkdir airflow
             cd airflow
             pipenv --python 3.8
             pipenv shell
             export AIRFLOW_HOME=$(pwd)
             pipenv install apache-airflow
             pipenv install apache-airflow-providers-databricks
             mkdir dags
             airflow db init
             airflow users create --username admin --firstname <firstname> --lastname <lastname> --role Admin --email <email>
